from typing import Dict, Any, Union
from datetime import datetime
import io

class ReportGenerator:
    """Generates comprehensive CV analysis reports in multiple formats"""
    
    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate_report(self, analysis: Dict[str, Any], original_filename: str, format_type: str = 'txt') -> Union[str, bytes]:
        """Generate a comprehensive CV analysis report in specified format"""
        
        if format_type.lower() == 'pdf':
            return self._generate_pdf_report(analysis, original_filename)
        else:
            return self._generate_txt_report(analysis, original_filename)
    
    def _generate_txt_report(self, analysis: Dict[str, Any], original_filename: str) -> str:
        """Generate a text-based CV analysis report"""
        
        report_lines = []
        
        # Header
        report_lines.extend([
            "=" * 80,
            "CVNalys - Professional CV Analysis Report",
            "=" * 80,
            f"Generated on: {self.timestamp}",
            f"Original CV: {original_filename}",
            "",
            ""
        ])
        
        # Executive Summary
        score = analysis.get('score', 'N/A')
        score_text = f"{score}/100 ({score}%)" if score != 'N/A' else "N/A"
        report_lines.extend([
            "EXECUTIVE SUMMARY",
            "-" * 40,
            f"Overall CV Score: {score_text}",
            "",
            self._generate_summary(analysis),
            "",
            ""
        ])
        
        # Detailed Analysis
        report_lines.extend([
            "DETAILED ANALYSIS",
            "-" * 40,
            ""
        ])
        
        # Basic Analysis Section
        basic_analysis = analysis.get('basic_analysis', {})
        report_lines.extend(self._format_basic_analysis(basic_analysis))
        report_lines.append("")
        
        # Skills Analysis
        skills = basic_analysis.get('skills', {})
        if skills:
            report_lines.extend(self._format_skills_analysis(skills))
            report_lines.append("")
        
        # AI Insights
        ai_analysis = analysis.get('ai_analysis', {})
        if ai_analysis.get('ai_insights'):
            report_lines.extend([
                "AI-POWERED INSIGHTS",
                "-" * 40,
                ai_analysis['ai_insights'],
                ""
            ])
        
        # Recommendations
        recommendations = analysis.get('recommendations', [])
        if recommendations:
            report_lines.extend(self._format_recommendations(recommendations))
            report_lines.append("")
        
        # Action Plan
        report_lines.extend(self._generate_action_plan(analysis))
        
        # Footer
        report_lines.extend([
            "",
            "=" * 80,
            "Report generated by CVNalys - Professional CV Analysis Tool",
            "Powered by SISU AI",
            "=" * 80
        ])
        
        return "\n".join(report_lines)
    
    def _generate_pdf_report(self, analysis: Dict[str, Any], original_filename: str) -> bytes:
        """Generate a PDF-based CV analysis report"""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors
            from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
            
            # Create a buffer to store the PDF
            buffer = io.BytesIO()
            
            # Create the PDF document
            doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
            
            # Get styles
            styles = getSampleStyleSheet()
            
            # Create custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                spaceAfter=30,
                alignment=TA_CENTER,
                textColor=colors.HexColor('#1e40af')
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                spaceAfter=12,
                spaceBefore=20,
                textColor=colors.HexColor('#374151')
            )
            
            subheading_style = ParagraphStyle(
                'CustomSubHeading',
                parent=styles['Heading3'],
                fontSize=14,
                spaceAfter=8,
                spaceBefore=16,
                textColor=colors.HexColor('#6b7280')
            )
            
            normal_style = ParagraphStyle(
                'CustomNormal',
                parent=styles['Normal'],
                fontSize=11,
                spaceAfter=6,
                alignment=TA_JUSTIFY
            )
            
            # Build the story (content)
            story = []
            
            # Title
            story.append(Paragraph("CVNalys - Professional CV Analysis Report", title_style))
            story.append(Spacer(1, 20))
            
            # Header info
            story.append(Paragraph(f"<b>Generated on:</b> {self.timestamp}", normal_style))
            story.append(Paragraph(f"<b>Original CV:</b> {original_filename}", normal_style))
            story.append(Spacer(1, 20))
            
            # Executive Summary
            story.append(Paragraph("EXECUTIVE SUMMARY", heading_style))
            score = analysis.get('score', 'N/A')
            score_text = f"{score}/100 ({score}%)" if score != 'N/A' else "N/A"
            story.append(Paragraph(f"<b>Overall CV Score:</b> {score_text}", normal_style))
            story.append(Spacer(1, 12))
            story.append(Paragraph(self._generate_summary(analysis), normal_style))
            story.append(Spacer(1, 20))
            
            # Detailed Analysis
            story.append(Paragraph("DETAILED ANALYSIS", heading_style))
            story.append(Spacer(1, 12))
            
            # Basic Analysis
            basic_analysis = analysis.get('basic_analysis', {})
            story.extend(self._format_pdf_basic_analysis(basic_analysis, normal_style, subheading_style))
            
            # Skills Analysis
            skills = basic_analysis.get('skills', {})
            if skills:
                story.extend(self._format_pdf_skills_analysis(skills, normal_style, subheading_style))
            
            # AI Insights
            ai_analysis = analysis.get('ai_analysis', {})
            if ai_analysis.get('ai_insights'):
                story.append(Paragraph("AI-POWERED INSIGHTS", heading_style))
                story.append(Spacer(1, 12))
                # Clean AI insights text for PDF
                ai_text = ai_analysis['ai_insights'].replace('\n', '<br/>')
                story.append(Paragraph(ai_text, normal_style))
                story.append(Spacer(1, 20))
            
            # Recommendations
            recommendations = analysis.get('recommendations', [])
            if recommendations:
                story.extend(self._format_pdf_recommendations(recommendations, normal_style, heading_style))
            
            # Action Plan
            story.extend(self._format_pdf_action_plan(analysis, normal_style, heading_style, subheading_style))
            
            # Footer
            story.append(Spacer(1, 30))
            story.append(Paragraph("Report generated by CVNalys - Professional CV Analysis Tool", normal_style))
            story.append(Paragraph("Powered by SISU AI", normal_style))
            
            # Build the PDF
            doc.build(story)
            
            # Get the PDF content
            pdf_content = buffer.getvalue()
            buffer.close()
            
            return pdf_content
            
        except ImportError as e:
            print(f"ReportLab not available: {e}")
            # Fallback to text if reportlab is not available
            return self._generate_txt_report(analysis, original_filename).encode('utf-8')
        except Exception as e:
            print(f"PDF generation failed: {e}")
            # Fallback to text on any error
            return self._generate_txt_report(analysis, original_filename).encode('utf-8')
    
    def _format_pdf_basic_analysis(self, basic_analysis: Dict[str, Any], normal_style, subheading_style):
        """Format basic analysis for PDF"""
        from reportlab.platypus import Paragraph, Spacer
        
        story = []
        
        # Document Statistics
        story.append(Paragraph("DOCUMENT STATISTICS", subheading_style))
        story.append(Spacer(1, 8))
        
        word_count = basic_analysis.get('word_count', 0)
        sentence_count = basic_analysis.get('sentence_count', 0)
        
        story.append(Paragraph(f"<b>Total Words:</b> {word_count}", normal_style))
        story.append(Paragraph(f"<b>Total Sentences:</b> {sentence_count}", normal_style))
        story.append(Spacer(1, 16))
        
        # Contact Information
        contact_info = basic_analysis.get('contact_info', {})
        if contact_info:
            story.append(Paragraph("CONTACT INFORMATION", subheading_style))
            story.append(Spacer(1, 8))
            
            emails = contact_info.get('emails', [])
            if emails:
                story.append(Paragraph(f"<b>Email Addresses:</b> {', '.join(emails)}", normal_style))
            
            phones = contact_info.get('phones', [])
            if phones:
                story.append(Paragraph(f"<b>Phone Numbers:</b> {', '.join(phones)}", normal_style))
            
            story.append(Spacer(1, 16))
        
        # Content Indicators
        education_count = basic_analysis.get('education_indicators', 0)
        experience_count = basic_analysis.get('experience_indicators', 0)
        
        story.append(Paragraph("CONTENT INDICATORS", subheading_style))
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>Education References:</b> {education_count}", normal_style))
        story.append(Paragraph(f"<b>Experience References:</b> {experience_count}", normal_style))
        story.append(Spacer(1, 16))
        
        return story
    
    def _format_pdf_skills_analysis(self, skills: Dict[str, list], normal_style, subheading_style):
        """Format skills analysis for PDF"""
        from reportlab.platypus import Paragraph, Spacer
        
        story = []
        story.append(Paragraph("SKILLS ANALYSIS", subheading_style))
        story.append(Spacer(1, 8))
        
        for category, skill_list in skills.items():
            if skill_list:
                category_name = category.replace('_', ' ').title()
                story.append(Paragraph(f"<b>{category_name}:</b>", normal_style))
                story.append(Paragraph(f"  {', '.join(skill_list)}", normal_style))
                story.append(Spacer(1, 8))
        
        story.append(Spacer(1, 8))
        return story
    
    def _format_pdf_recommendations(self, recommendations: list, normal_style, heading_style):
        """Format recommendations for PDF"""
        from reportlab.platypus import Paragraph, Spacer
        
        story = []
        story.append(Paragraph("RECOMMENDATIONS FOR IMPROVEMENT", heading_style))
        story.append(Spacer(1, 12))
        
        for i, recommendation in enumerate(recommendations, 1):
            story.append(Paragraph(f"{i}. {recommendation}", normal_style))
        
        story.append(Spacer(1, 16))
        return story
    
    def _format_pdf_action_plan(self, analysis: Dict[str, Any], normal_style, heading_style, subheading_style):
        """Format action plan for PDF"""
        from reportlab.platypus import Paragraph, Spacer
        
        story = []
        story.append(Paragraph("ACTION PLAN", heading_style))
        story.append(Spacer(1, 12))
        
        score = analysis.get('score', 0)
        basic = analysis.get('basic_analysis', {})
        
        # Priority actions based on score
        if score < 50:
            story.append(Paragraph("HIGH PRIORITY:", subheading_style))
            story.append(Paragraph("• Review and rewrite CV content for clarity and impact", normal_style))
            story.append(Paragraph("• Ensure all contact information is current and professional", normal_style))
            story.append(Paragraph("• Add specific skills and achievements with quantifiable results", normal_style))
        elif score < 75:
            story.append(Paragraph("MEDIUM PRIORITY:", subheading_style))
            story.append(Paragraph("• Enhance skills section with industry-specific keywords", normal_style))
            story.append(Paragraph("• Improve formatting and visual presentation", normal_style))
            story.append(Paragraph("• Add more specific examples of achievements", normal_style))
        else:
            story.append(Paragraph("LOW PRIORITY:", subheading_style))
            story.append(Paragraph("• Fine-tune content for specific job applications", normal_style))
            story.append(Paragraph("• Consider adding industry-specific certifications", normal_style))
            story.append(Paragraph("• Optimize for ATS (Applicant Tracking Systems)", normal_style))
        
        story.append(Spacer(1, 12))
        
        # Specific actions based on analysis
        if not basic.get('has_contact_info', False):
            story.append(Paragraph("• Add professional email and phone number", normal_style))
        
        if not basic.get('has_skills', False):
            story.append(Paragraph("• Include relevant technical and soft skills", normal_style))
        
        word_count = basic.get('word_count', 0)
        if word_count < 100:
            story.append(Paragraph("• Expand content with more detailed experience descriptions", normal_style))
        elif word_count > 500:
            story.append(Paragraph("• Condense content to focus on most relevant information", normal_style))
        
        story.append(Spacer(1, 12))
        story.append(Paragraph("Next Steps:", subheading_style))
        story.append(Paragraph("1. Implement the recommendations above", normal_style))
        story.append(Paragraph("2. Have your CV reviewed by a professional", normal_style))
        story.append(Paragraph("3. Tailor your CV for specific job applications", normal_style))
        story.append(Paragraph("4. Consider professional CV writing services if needed", normal_style))
        
        return story
    
    def _generate_summary(self, analysis: Dict[str, Any]) -> str:
        """Generate an executive summary"""
        score = analysis.get('score', 0)
        basic = analysis.get('basic_analysis', {})
        
        summary_parts = []
        
        if score >= 80:
            summary_parts.append("Excellent CV quality with strong professional presentation.")
        elif score >= 60:
            summary_parts.append("Good CV quality with room for improvement in key areas.")
        elif score >= 40:
            summary_parts.append("CV needs significant improvement to be competitive.")
        else:
            summary_parts.append("CV requires substantial revision to meet professional standards.")
        
        # Add key metrics
        word_count = basic.get('word_count', 0)
        if word_count > 0:
            summary_parts.append(f"Document contains {word_count} words.")
        
        has_contact = basic.get('has_contact_info', False)
        if has_contact:
            summary_parts.append("Contact information is properly included.")
        else:
            summary_parts.append("Contact information is missing or incomplete.")
        
        has_skills = basic.get('has_skills', False)
        if has_skills:
            summary_parts.append("Skills are well-documented.")
        else:
            summary_parts.append("Skills section needs enhancement.")
        
        return " ".join(summary_parts)
    
    def _format_basic_analysis(self, basic_analysis: Dict[str, Any]) -> list:
        """Format basic analysis section"""
        lines = [
            "DOCUMENT STATISTICS",
            "-" * 30
        ]
        
        # Word and sentence count
        word_count = basic_analysis.get('word_count', 0)
        sentence_count = basic_analysis.get('sentence_count', 0)
        
        lines.extend([
            f"Total Words: {word_count}",
            f"Total Sentences: {sentence_count}",
            ""
        ])
        
        # Contact information
        contact_info = basic_analysis.get('contact_info', {})
        if contact_info:
            lines.extend([
                "CONTACT INFORMATION",
                "-" * 30
            ])
            
            emails = contact_info.get('emails', [])
            if emails:
                lines.append(f"Email Addresses: {', '.join(emails)}")
            
            phones = contact_info.get('phones', [])
            if phones:
                lines.append(f"Phone Numbers: {', '.join(phones)}")
            
            lines.append("")
        
        # Education and experience indicators
        education_count = basic_analysis.get('education_indicators', 0)
        experience_count = basic_analysis.get('experience_indicators', 0)
        
        lines.extend([
            "CONTENT INDICATORS",
            "-" * 30,
            f"Education References: {education_count}",
            f"Experience References: {experience_count}",
            ""
        ])
        
        return lines
    
    def _format_skills_analysis(self, skills: Dict[str, list]) -> list:
        """Format skills analysis section"""
        lines = [
            "SKILLS ANALYSIS",
            "-" * 30
        ]
        
        for category, skill_list in skills.items():
            if skill_list:
                category_name = category.replace('_', ' ').title()
                lines.extend([
                    f"{category_name}:",
                    f"  {', '.join(skill_list)}",
                    ""
                ])
        
        return lines
    
    def _format_recommendations(self, recommendations: list) -> list:
        """Format recommendations section"""
        lines = [
            "RECOMMENDATIONS FOR IMPROVEMENT",
            "-" * 40
        ]
        
        for i, recommendation in enumerate(recommendations, 1):
            lines.append(f"{i}. {recommendation}")
        
        return lines
    
    def _generate_action_plan(self, analysis: Dict[str, Any]) -> list:
        """Generate an action plan based on analysis"""
        lines = [
            "ACTION PLAN",
            "-" * 40
        ]
        
        score = analysis.get('score', 0)
        basic = analysis.get('basic_analysis', {})
        
        # Priority actions based on score
        if score < 50:
            lines.extend([
                "HIGH PRIORITY:",
                "• Review and rewrite CV content for clarity and impact",
                "• Ensure all contact information is current and professional",
                "• Add specific skills and achievements with quantifiable results",
                ""
            ])
        elif score < 75:
            lines.extend([
                "MEDIUM PRIORITY:",
                "• Enhance skills section with industry-specific keywords",
                "• Improve formatting and visual presentation",
                "• Add more specific examples of achievements",
                ""
            ])
        else:
            lines.extend([
                "LOW PRIORITY:",
                "• Fine-tune content for specific job applications",
                "• Consider adding industry-specific certifications",
                "• Optimize for ATS (Applicant Tracking Systems)",
                ""
            ])
        
        # Specific actions based on analysis
        if not basic.get('has_contact_info', False):
            lines.append("• Add professional email and phone number")
        
        if not basic.get('has_skills', False):
            lines.append("• Include relevant technical and soft skills")
        
        word_count = basic.get('word_count', 0)
        if word_count < 100:
            lines.append("• Expand content with more detailed experience descriptions")
        elif word_count > 500:
            lines.append("• Condense content to focus on most relevant information")
        
        lines.append("")
        lines.append("Next Steps:")
        lines.append("1. Implement the recommendations above")
        lines.append("2. Have your CV reviewed by a professional")
        lines.append("3. Tailor your CV for specific job applications")
        lines.append("4. Consider professional CV writing services if needed")
        
        return lines
